### ISSUE TITLE
Error: No available formula with the name "rbenv-gem-rehash" 

### ISSUE THREAD

**Issue by ggomesfe** [IcaliaLabs/kaishi#14]
I got this error when the script tries to install rbenv. I've tried run 'brew update' but no success. Any ideia?

**Comment by kurenn** [comment]
It seems like the formula is not available anymore, checkout https://github.com/rbenv/rbenv-gem-rehash and please let me know how it goes!

**Comment by grenti** [comment]
Can we have the this step removed from the script or made optional? The rbenv-gem-rehash repo doesn't address it's deprecation at all.

**Comment by kurenn** [comment]
I'll change the installation source from brew to github

**Comment by kurenn** [comment]
Just made the change, check it out on this [commit](https://github.com/IcaliaLabs/kaishi/commit/14b48b852d3ebad37e8bd7b5db3571c8d30fc908)

**Comment by grenti** [comment]
Sorry I didn't check this out earlier, looks good! Thank you @kurenn!

**Comment by kurenn** [comment]
Sure!
