### ISSUE TITLE
Error: Unknown command: services-- 'brew services' no longer supported

### ISSUE THREAD

**Issue by gabehoffman** [IcaliaLabs/kaishi#2]
You already have Oh My Zsh installed. 
You'll need to remove /Volumes/Storage/Users/gabehoffman/.oh-my-zsh if you want to install

You already have Homebrew installed...good job!

Updating brew formulas
Already up-to-date.

Installing git for control version
Warning: git-2.1.2 already installed

Installing postgresql for database management
Warning: postgresql-9.3.5_1 already installed

Installing vim with Homebrew for latest version
Warning: vim-7.4.430_1 already installed

Installing image magick for image processing
Warning: imagemagick-6.8.9-7 already installed

Starting postgres...
Error: Unknown command: services

Trying to follow along with your tutorial, but on both my Yosemite updated machines I'm getting this.

**Comment by mrsantucci** [comment]
@AlJohri Excellent!

**Comment by AlJohri** [comment]
No, I currently use this approach:

https://github.com/thoughtbot/laptop/blob/master/mac#L90

```bash
brew_launchctl_restart() {
  local name="$(brew_expand_alias "$1")"
  local domain="homebrew.mxcl.$name"
  local plist="$domain.plist"

  fancy_echo "Restarting %s ..." "$1"
  mkdir -p "$HOME/Library/LaunchAgents"
  ln -sfv "/usr/local/opt/$name/$plist" "$HOME/Library/LaunchAgents"

  if launchctl list | grep -Fq "$domain"; then
    launchctl unload "$HOME/Library/LaunchAgents/$plist" >/dev/null
  fi
  launchctl load "$HOME/Library/LaunchAgents/$plist" >/dev/null
}
```

**Comment by kurenn** [comment]
Thanks for sharing @AlJohri ! does this works on yosemite?, if so, maybe you can place a pull request, how about that? =)

**Comment by milan-chen** [comment]
thx!!! @AlJohri
