### ISSUE TITLE
line 152

### ISSUE THREAD

**Issue by zenbakiak** [IcaliaLabs/kaishi#4]
pretty_print "Installing custom Rails app generator from Icalia"
  curl -L https://raw2.github.com/IcaliaLabs/railsAppCustomGenerator/master/install.sh | sh

log:
sh: line 1: syntax error near unexpected token `newline'
sh: line 1: `<!DOCTYPE html>'

**Comment by kurenn** [comment]
We removed that line as it was giving a lot of trouble to some others
